# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'download' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for download

pod 'AFNetworking','3.2.1'

  target 'downloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'downloadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
